config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :users do
    post 'addfollower/:id' => 'users#add_follower', as: :add_follower, on: :collection
    delete 'unfollow/:id' => 'users#unfollow', as: :unfollow, on: :collection
    get 'followers/:id' => 'users#followers', as: :followers, on: :collection
  end

  root 'users#index'

  post 'photos/create' => 'photos#create', as: :create_photo

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { medium: "200x200#", thumb: "100x100#", large: "372x349#" }

  validates_attachment_presence :image
  validates_attachment_file_name :image, :matches => [/png\Z/i, /jpe?g\Z/i, /gif\Z/i]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos, dependent: :destroy
  has_many :users_relation, class: UsersRelation
  has_many :follower_users, class: User, through: :users_relation, foreign_key: :follower_user_id

  validates :email, presence: true, uniqueness: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, presence: true, confirmation: true, length: { within: 6..40 }
  validates :avatar, presence: true

  after_initialize :set_defaults

  def set_defaults
    self.avatar ||= "noAvatar.jpg"
  end  
end

app/models/users_relation.rb
class UsersRelation < ActiveRecord::Base
  belongs_to :follower_user, class: User
  belongs_to :user

  validates :follower_user_id, presence: true
  validates :user_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :store_location

  def store_location
    # store last url - this is needed for post-login redirect to whatever the user last visited.
    if (request.fullpath != "/users/sign_in" &&
        request.fullpath != "/users/sign_up" &&
        request.fullpath != "/users/password" &&
        request.fullpath != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls

      session[:previous_url] = new_purchase_path(params["product"]) if params["product"]   
   end
 end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end


  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  
  def create
    photo = Photo.new({ name: photo_params[:image].original_filename, user_id: current_user.id, image: photo_params[:image] })
    if !photo_params[:description].nil? && !photo_params[:description].empty?
      photo.description = photo_params[:description]
    end
    unless photo.save
      render "shared/something_went_wrong"
    end
    @photos = current_user.photos.order("updated_at DESC").limit(100)
    render partial: "shared/user_photos"
  end

private
  def photo_params
    params.require(:photo).permit(:image, :name, :description)
  end    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @photo_news = Photo.joins("JOIN users ON users.id = photos.user_id
                               JOIN users_relations ur ON ur.user_id = users.id") 
                              .where(ur: { follower_user_id: current_user.id })
                              .order("photos.updated_at DESC").limit(100)
  end

  def show
    if params[:id].nil? || params[:id].empty?
      @user = current_user
    else
      @user = User.find(params[:id])
    end
    @photos = @user.photos.order("updated_at DESC").limit(100)
    if @photos.count > 3
      @title_photos = @photos.sample(3)
    end
    @photo = Photo.new
  end

  def add_follower
    relation = UsersRelation.new({ follower_user_id: current_user.id, user_id: params[:id].to_i })
    unless relation.save
      render "shared/something_went_wrong"
    end    
    render partial: "users/unfollow_btn"
  end

  def unfollow
    unless UsersRelation.where({ follower_user_id: current_user.id, user_id: params[:id].to_i }).destroy_all
      render "shared/something_went_wrong"
    end
    render partial: "users/follow_btn"
  end

  def followers
    @followers = current_user.follower_users
    @i_follow = User.joins(:users_relation).where(users_relations: { follower_user_id: current_user.id } )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class='width55 align-center'>    
      <div class="navbar-header">
        <button type="button" class="btn btn-default navbar-toggle collapsed">            
        </button>
        <a <%= "href=#{users_path}" %> class="navbar-brand"><span class="glyphicon glyphicon-home"></span></a>
      </div>
      <ul class="nav navbar-nav margin-left36">
        <li>
          <a <%= "href=#{users_path}" %> class="vertical-paddings5px"><%= image_tag 'instagram.png', { size: "115x40" } %></a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=current_user.firstname%></a>
          <ul class="dropdown-menu" role="menu">
            <li><a <%= "href=#{user_path(current_user.id)}" %>>View Profile</a></li>
            <li><a <%= "href=#{followers_users_path(current_user.id)}" %>>View Followers</a></li>
            <li><a href="#">Edit Profile</a></li>
            <li><%= link_to "Log Out", destroy_user_session_path, { method: :delete } %></li>            
          </ul>
        </li>
      </ul>
  </div>
</nav>

app/views/shared/_user_photos.html.erb
<div class="user-photos">
  <% if @photos.empty? %>
    <% if !@user.nil? && @user.id == current_user.id %>
      <% personality = "You have" %>
    <% elsif !@user.nil? && @user.id != current_user.id %>
      <% personality = @user.firstname + " has" %>
    <% end %>
      <div class="text-align-center well alert-info" role="alert"><%= personality %> no uploaded photos yet.</div>
  <% else %>
      <% @photos.each_with_index do |photo, index| %>
        <div class="photo-body">
          <%= image_tag photo.image.url(:medium), class: "img-thumbnail img-rounded user-image" %>
        </div>
        <% if (index+1) % 5 == 0  && index != 0%>
          <hr class="clear-both">
        <% end %>
      <% end %>
  <% end %>
</div>

app/views/users/_avatar.html.erb
<div class="avatar">
  <%= image_tag @user.avatar, { alt: @user.firstname, id: "avatar-image" } %>
  <% if @user.id == current_user.id %>
    <a href="#">
      <button id="edit-profile" class="btn btn-default avatar-button">Edit Profile</button>
    </a>
  <% else %>
    <% if UsersRelation.where(user_id: @user.id, follower_user_id: current_user.id).first.nil? %>
      <%= render partial: "users/follow_btn" %>
    <% else %>    
      <%= render partial: "users/unfollow_btn" %>
    <% end %>
  <% end %>
</div>

app/views/users/_follow_btn.html.erb
<button id="av-btn-follow" class="btn btn-default avatar-button">Follow</button>

app/views/users/_unfollow_btn.html.erb
<button id="av-btn-following" class="btn btn-default avatar-button">Unfollow</button>

app/views/users/_users_list.html.erb
<% if button %>
  <% width = "width55" %>
<% else %>
  <% width = "width77" %>
<% end %>
<% users.each do |user| %>
  <div class="connected_user"> 
    <a <%= "href=#{user_path(user)}" %>>
      <%= image_tag user.avatar, { alt: user.firstname, class: "float-left" } %>
    </a>
    <div class="user-data <%= "#{width}" %>">
      <p class="name"><b><%= "#{user.firstname} #{user.lastname}" %></b></p>
      <p><small><%= "#{user.status}" %></small></p>
      <p>Photos: <%= user.photos.count %> </p>
    </div>
    <% if button %>
      <button class="btn btn-default avatar-button" <%= "value=#{user.id}" %>>Unfollow</button>
    <% end %>
  </div>
  <% unless user == users.last %>
    <hr>
  <% end %>
<% end %>

app/views/users/followers.html.erb
<%= render partial: 'shared/header' %>
<ul class="nav nav-tabs followers-tabs" role="tablist">
  <li class="active"><a href="#followers" role="tab" data-toggle="tab">Followers</a></li>
  <li><a href="#i-follow" role="tab" data-toggle="tab">I follow</a></li>
</ul>
<div class="tab-content followers-tabs">
  <div class="tab-pane active" id="followers">
    <%= render partial: "users_list", locals: { users: @followers, button: false } %>
  </div>
  <div class="tab-pane" id="i-follow">
    <%= render partial: "users_list", locals: { users: @i_follow, button: true } %>
  </div>
</div>

app/views/users/index.html.erb
<%= render partial: 'shared/header' %>
<div class="feed">
  <% if @photo_news.empty? %>
    <div class="text-align-center well alert-info" role="alert">You don't follow any user yet.</div>
  <% else %>
    <% @photo_news.each do |photo| %>
      <div class="news-item">
        <a <%= "href=#{user_path(photo.user)}"%>><p><%= "#{photo.user.firstname} #{photo.user.lastname}" %></p></a>
        <div class="position-relative">
        <%= image_tag photo.user.avatar, { alt: photo.user.firstname, id: "news-avatar-image", class: "img-rounded " } %>      
      </div>
        <%= image_tag photo.image.url(:large), class: "news-item-image" %>
        <p class="news-time"><%= photo.updated_at.strftime("%d %b. %Y") %> </p>
        <p class="news-time"><%= photo.updated_at.strftime("%H:%M") %> </p>
      </div>
      <hr>
    <% end %>
  <% end %>
</feed>

app/views/users/show.html.erb
<div id="page-color-grey">&nbsp;</div>
<%= render partial: 'shared/header' %>
<div class="width100">
  <% unless @title_photos.nil? %>  
    <div class="header width100">
      <div class="user-news">
        <div class="title-image">
          <%= image_tag @title_photos[0].image.url(:large) %>
        </div>
        <div class="title-image">
          <%= image_tag @title_photos[1].image.url(:large) %>
        </div>
        <div class="title-image" id="title-image-rigth">
          <%= image_tag @title_photos[2].image.url(:large) %>
        </div>        
      </div>
    </div>
  <% else %>
    <div class="header width100 height10em">
      <div class="user-news height7em">
      </div>
    </div>    
  <% end %>
  <div class="body">
    <div id="user-data">
      <%= render partial: "avatar" %>      
      <div id="user-status">
        <h4><%= @user.firstname+" "+@user.lastname %></h4>
        <p><%= @user.status %></p>
      </div>
      <nav class="navbar navbar-default" id="user-stats">
        <ul class="nav navbar-nav width-inherit height50px">
          <li class="navbar-text width23"><p id="photos-number"><%= @photos.count %></p><small class="help-block">photos</small></li>
          <li class="divider-vertical"></li>
          <li class="navbar-text width23"><%= 0 %><small class="help-block">followers</small></li>
          <li class="divider-vertical"></li>
          <li class="navbar-text width23"><%= 0 %><small class="help-block">following</small></li>
        </ul>
      </nav>      
      <% if current_user == @user %>
        <%= form_for @photo, remote: true, url: create_photo_path, method: :post, html: { multipart: true, id: "photo-upload-from" } do |f| %>
          <input type="file" class="filestyle" data-input="false" id="photo_image" name="photo[image]" data-buttonText="Add Photo"
                 data-iconName="glyphicon-camera" data-badge="false" >
           <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %> 
        <% end %>
      <% end %>
    </div>
    <%= render partial: "shared/user_photos" %>
  </div>
</div>

<script type="text/javascript">
  user = {
    id: "<%= @user.id %>"
  }
</script>